---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'squid3'
    - 'lightsquid'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
